### ISSUE TITLE
Support for runes

### ISSUE THREAD

**Issue by mxdvl** [zed-extensions/svelte#12]
Svelte 5 supports [**runes**](https://svelte.dev/blog/runes), but they appear not to be recognised in Zed. I surmise this is down to the `svelte-language-server` somehow not being on the latest version? I would happily provide support/testing if helpful.

One thing to note is that I do not use Node, but rather Deno for setting up my project, so there’s no `node_modules` folder in my repo, which means it’s [unlikely the extension finds it](https://github.com/zed-extensions/svelte/blob/a3ed9a8de91a02ca550bb34e415d5818b5a62e74/src/svelte.rs#L18-L20).

**Comment by mxdvl** [comment]
Fixed it with `deno install npm:svelte --node-modules-dir` which ensured the LSP worked fine.

**Comment by x4fingers** [comment]
@mxdvl I don't think it has been done yet. I still face this issue with my project using Bun runtime, it had `node_modules` folder

**Comment by mxdvl** [comment]
If you can get a reproducible example feel free to reopen!
